name: template #CHANGE for your project
channels:
  - conda-forge
dependencies:
# Add explicit version numbers to freeze a dependency.
# The format accepts "package=version" or "package>=version"
# with no spaces around the "=" or ">=".
# e.g. - python=3.10.6
  - python 
  - pyyaml 
  - numpy
  - matplotlib
  - gitpython
  - termcolor
  - colorama
  - jupyter
  - linearmodels
  # - julia 
  # - pip
  # - pip: # if there is a package available via pip but not with conda, can import like this:
  - r
  - r-tidyverse
  - r-dplyr
  - r-irkernel
  - r-caret
  - r-ggplot2
  - r-zipcoder
  - r-viridis
  - r-ggthemes
  - r-ggtext
  - r-ggmap